### ISSUE TITLE
Geklaut??

### ISSUE THREAD

**Issue by ForYaSee** [NutellaBoiii/JDA-DiscordBot#2]
Mir kommt der Bot sehr bekannt vor. Kann es sein, dass der von https://github.com/zekroTJA geforkt ist?

**Comment by GregTCLTK** [comment]
Mir auch

**Comment by Crypti-x** [comment]
Das stimmt

**Comment by NutellaBoiii** [comment]
Dieser Beitrag wurde geschlossen, da bald ein Statement kommt.
